FORMAT: 1A
HOST: http://diagnostic.api/

# Diagnostic Api
Diagnotic api designed for share information about openstack's installations


# Group Notes
Notes related resources of the **Notes API**

## Openstack Collection [/openstack]
### List all Openstack installations [GET]
+ Response 200 (application/json)

        [{
          "id": 0, "name": "customer0" 
        }, {
          "id": 1, "name": "customer1"
        }]

### Create a Openstack installation [POST]
+ Request (application/json)

        { "name": "customer3" }

+ Response 201 (application/json)

        { "id": 2, "name": "customer3" }

## Openstack cluster [/openstack/{id}]
### A single openstack object with all available information        

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Openstack installation to perform action with. Has example value.

### Retrieve a Openstack [GET]
+ Response 200 (application/json)

    + Body

            { "id": 2, "elements": ["hw"] }

### Remove a Openstack [DELETE]
+ Response 204

## Openstack cluster hardware [/openstack/{id}/hw]
### A single openstack object with detailed information about hardware configuration of the cluster       

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Openstack installation to perform action with. Has example value.

### Retrieve a Openstack [GET]
+ Response 200 (application/json)

    + Body

            { "elements": ["node0", "node1", "node2"] }

### Remove a Openstack [DELETE]
+ Response 204

## Openstack cluster node [/openstack/{id}/hw/node0]
### A single node object with all available information about hardware configuration of the node in the OpenStack cluster

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Openstack installation to perform action with. Has example value.

### Retrieve a Openstack [GET]
+ Response 200 (application/json)

    + Body

            { "elements": ["cpu", "memory", "nic"] }

### Remove a Openstack [DELETE]
+ Response 204

## Openstack [/openstack/{id}/hw/node0/cpu]
### A single openstack object with all available information          

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Openstack installation to perform action with. Has example value.

### Retrieve a Openstack [GET]
+ Response 200 (application/json)

    + Body

            { "elements": ["cpu0", "cpu1", "cpu2", "cpu3"] }

### Remove a Openstack [DELETE]
+ Response 204

## Openstack [/openstack/{id}/hw/node0/cpu/cpu0]
### A single openstack object with all available information          

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Openstack installation to perform action with. Has example value.

### Retrieve a Openstack [GET]
+ Response 200 (application/json)

    + Body

            { "elements": [ { "Name":  "Quad core Intel Core i5-3470 CPU", "cores" : 4, "freq" : 1600} ] }

### Remove a Openstack [DELETE]
+ Response 204

## Openstack [/openstack/{id}/hw/node0/memory]
### A single openstack object with all available information          

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Openstack installation to perform action with. Has example value.

### Retrieve a Openstack [GET]
+ Response 200 (application/json)

    + Body

            { "elements": [ "total": 7673 ] }

### Remove a Openstack [DELETE]
+ Response 204

